# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: artifact
          path: ./dist/*
          if-no-files-found: error
          # Duration after which artifact will expire in days. 0 means using default retention.
          # Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          retention-days: 30
          include-hidden-files: true
          
  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         registry-url: https://npm.pkg.github.com/
  #     - uses: pnpm/action-setup@v4.0.0
  #       with:
  #         version: 9
  #         run_install: true
          
  #     - run: pnpm ci
  #     - run: pnpm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
